safety_judge_model:
  responses_api_models:
    vllm_model:
      entrypoint: app.py
      base_url: http://<host_url>:<port>/v1
      api_key: <api_key>
      model: nvidia/Nemotron-Content-Safety-Reasoning-4B
      return_token_id_information: false
      uses_reasoning_parser: true