policy_model:
  responses_api_models:
    local_vllm_model:
      entrypoint: app.py
      model: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
      return_token_id_information: false
      uses_reasoning_parser: true
      replace_developer_role_with_system: false
      debug: false

      extra_body:
        temperature: 1.0
        top_p: 1.0
        max_output_tokens: null

      hf_home: null

      vllm_serve_env_vars:
        VLLM_RAY_DP_PACK_STRATEGY: strict

      vllm_serve_kwargs:
        data_parallel_size: 1
        tensor_parallel_size: 2
        pipeline_parallel_size: 1

        trust_remote_code: true
        mamba_ssm_cache_dtype: float32
        gpu_memory_utilization: 0.9
        enable_auto_tool_choice: true
        tool_call_parser: qwen3_coder
        reasoning_parser: deepseek_r1
        model_loader_extra_config:
          enable_multithread_load: true
          num_threads: 16
